### ISSUE TITLE
Error when running with-process-isolation

### ISSUE THREAD

**Issue by diwu1989** [dmccombs/nosepipe#1]
I'm getting this error:

Traceback (most recent call last):
  File "/Users/diwu/.virtualenvs/BetterWorks/lib/python2.7/site-packages/nose/case.py", line 133, in run
    self.runTest(result)
  File "/Users/diwu/.virtualenvs/BetterWorks/lib/python2.7/site-packages/nose/case.py", line 151, in runTest
    test(result)
  File "/Users/diwu/.virtualenvs/BetterWorks/lib/python2.7/site-packages/nosepipe.py", line 173, in **call**
    (header + data).decode("latin1"))
Exception: short message body (want 1433299822, got 82)
Something went wrong
Message: Unknown command: '--with-process-isolation-reporter'
Type 'manage.py help' for usage.

**Comment by mdprewitt** [comment]
This is similar to what's happening here: https://github.com/dmccombs/nosepipe/pull/7

I have some time this week and will look into a similar solution.

**Comment by dmccombs** [comment]
@diwu1989 do you still run into this issue with the latest stable version of nosepipe given the fixes in #8 ?
